import { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import StorageProvider from "@/components/StorageProvider";

const wantedSans = localFont({
  src: [
    {
      path: "../../public/fonts/WantedSansStd-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/WantedSansStd-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-wanted-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${wantedSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <StorageProvider>
          {children}
        </StorageProvider>
      </body>
    </html>
  );
}
